export type Person = {
  nombre: string;
  apellido: string;
  usuario: string;
  email: string;
  telefonomovil: string;
  fechanacimiento: string;
  estado: string;
};

export const data: Person[] = <Person[]>[
  {
    nombre: "p1",
    apellido: "p1",
    email: "p1",
    estado: "p1",
    fechanacimiento: "p1",
    telefonomovil: "p1",
    usuario: "p1",
  },
  {
    nombre: "p1",
    apellido: "p1",
    email: "p1",
    estado: "p1",
    fechanacimiento: "p1",
    telefonomovil: "p1",
    usuario: "p1",
  },
  {
    nombre: "p1",
    apellido: "p1",
    email: "p1",
    estado: "p1",
    fechanacimiento: "p1",
    telefonomovil: "p1",
    usuario: "p1",
  },
  {
    nombre: "p1",
    apellido: "p1",
    email: "p1",
    estado: "p1",
    fechanacimiento: "p1",
    telefonomovil: "p1",
    usuario: "p1",
  },

  {
    nombre: "p1",
    apellido: "p1",
    email: "p1",
    estado: "p1",
    fechanacimiento: "p1",
    telefonomovil: "p1",
    usuario: "p1",
  },
  {
    nombre: "p1",
    apellido: "p1",
    email: "p1",
    estado: "p1",
    fechanacimiento: "p1",
    telefonomovil: "p1",
    usuario: "p1",
  },
  {
    nombre: "p1",
    apellido: "p1",
    email: "p1",
    estado: "p1",
    fechanacimiento: "p1",
    telefonomovil: "p1",
    usuario: "p1",
  },
  {
    nombre: "p1",
    apellido: "p1",
    email: "p1",
    estado: "p1",
    fechanacimiento: "p1",
    telefonomovil: "p1",
    usuario: "p1",
  },

  {
    nombre: "p1",
    apellido: "p1",
    email: "p1",
    estado: "p1",
    fechanacimiento: "p1",
    telefonomovil: "p1",
    usuario: "p1",
  },
  {
    nombre: "p1",
    apellido: "p1",
    email: "p1",
    estado: "p1",
    fechanacimiento: "p1",
    telefonomovil: "p1",
    usuario: "p1",
  },
  {
    nombre: "p1",
    apellido: "p1",
    email: "p1",
    estado: "p1",
    fechanacimiento: "p1",
    telefonomovil: "p1",
    usuario: "p1",
  },

  {
    nombre: "p1",
    apellido: "p1",
    email: "p1",
    estado: "p1",
    fechanacimiento: "p1",
    telefonomovil: "p1",
    usuario: "p1",
  },
  {
    nombre: "p1",
    apellido: "p1",
    email: "p1",
    estado: "p1",
    fechanacimiento: "p1",
    telefonomovil: "p1",
    usuario: "p1",
  },
  {
    nombre: "p1",
    apellido: "p1",
    email: "p1",
    estado: "p1",
    fechanacimiento: "p1",
    telefonomovil: "p1",
    usuario: "p1",
  },
  {
    nombre: "p1",
    apellido: "p1",
    email: "p1",
    estado: "p1",
    fechanacimiento: "p1",
    telefonomovil: "p1",
    usuario: "p1",
  },

  {
    nombre: "p1",
    apellido: "p1",
    email: "p1",
    estado: "p1",
    fechanacimiento: "p1",
    telefonomovil: "p1",
    usuario: "p1",
  },
  {
    nombre: "p1",
    apellido: "p1",
    email: "p1",
    estado: "p1",
    fechanacimiento: "p1",
    telefonomovil: "p1",
    usuario: "p1",
  },
  {
    nombre: "p1",
    apellido: "p1",
    email: "p1",
    estado: "p1",
    fechanacimiento: "p1",
    telefonomovil: "p1",
    usuario: "p1",
  },
  {
    nombre: "p1",
    apellido: "p1",
    email: "p1",
    estado: "p1",
    fechanacimiento: "p1",
    telefonomovil: "p1",
    usuario: "p1",
  },
];
