const MOBILE_VIEW = 360;
const MOBILE_VIEW_LANDSCAPE = 480;
const TABLE_VIEW = 768;
const TABLE_VIEW_LANDSCAPE = 1023;
const DESKTOP_VIEW = 1024;

export {
  MOBILE_VIEW,
  MOBILE_VIEW_LANDSCAPE,
  TABLE_VIEW,
  TABLE_VIEW_LANDSCAPE,
  DESKTOP_VIEW,
};
